name: openflix_client
description: A Netflix-like app built with Flutter using OMDB APIs and Bloc state management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # API & Networking
  http: ^1.1.0
  
  # UI & Design
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  
  # Utilities
  intl: ^0.18.1

  # Retrofit & Networking
  retrofit: ^4.0.0
  dio: ^5.4.0
  logger: ^2.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Retrofit Code Generation
  retrofit_generator: ^8.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true


